DANGER!  This is a big commit in the sense that it introduces multi-phase build support to Tinderbox.  This is designed to emulate exactly the way pointyhat builds with a phase for each of:
extract-depends
patch-depends
fetch-depends
build-depends
run-depends

I'm committing this untested for now in the hopes others will help me test.
Once the bugs get flushed out, this will become Tinderbox 2.0.

diff --git a/buildscript b/buildscript
--- a/buildscript
+++ b/buildscript
@@ -1,63 +1,158 @@
 #!/bin/sh
 
+# usage: $0 DIRNAME PHASE ED PD FD BD RD
+#   PHASE is 1 (checksum) or 2 (package)
+
+cleanup() {
+  status=$1
+
+  if [ -e ${dir}/.keep ]; then
+    cd ${dir}
+    objdir=$(make -V WRKDIR)
+    tar cfjC /tmp/work.tbz ${objdir}/.. work
+  fi
+
+  cat /tmp/make.log${status}
+  echo 1 > /tmp/status
+  echo "================================================================"
+  echo -n "build ended at "
+  date
+
+  exit 0
+}
+
+add_pkg() {
+  pkgs=$*
+
+  echo add_pkg $pkgs
+  cd /tmp/depends
+  export PKG_PATH=/tmp/depends
+  if [ ! -z "${pkgs}" ]; then
+    echo "adding dependencies"
+    for i in $pkgs; do
+      echo "pkg_add $i"
+      base=$(basename $i .tgz)
+      base=$(basename $base .tbz)
+      if pkg_info -q -e $base; then
+        echo "skipping $base, already added"
+      else
+        if ! pkg_add $i; then
+          echo "error in dependency $i, exiting"
+          echo "1" > /tmp/status
+          exit 1
+        fi
+      fi
+    done
+  fi
+}
+
+del_pkg() {
+  pkgs=$*
+
+  cd /tmp/depends
+  export PKG_PATH=/tmp/depends
+  if [ ! -z "${pkgs}" ]; then
+    unset delpkg
+    for i in $pkgs; do
+      base=$(basename $i .tgz)
+      base=$(basename $base .tbz)
+      if ! pkg_info -q -e $base; then
+        echo "skipping $base, already deleted"
+      else
+	delpkg="${base} ${delpkg}"
+      fi
+    done
+    echo "Deleting $delpkg"
+    if ! (echo ${delpkg} | xargs pkg_delete -rf); then
+      echo "error in pkg_delete, exiting"
+      echo "1" > /tmp/status
+      exit 1
+    fi
+  fi
+}
+
 dir=$1
 phase=$2
 
+ED=$3
+PD=$4
+FD=$5
+BD=$6
+RD=$7
+
 if [ $phase = 1 ]; then
 
-    cd $dir || exit 1
-    echo "maintained by: $(make maintainer)"
-    echo "build started at $(date)"
+  cd $dir || exit 1
+  echo "maintained by: $(make maintainer)"
+  echo "port directory: ${dir}"
+  echo "build started at $(date)"
 
-    cd /tmp/depends
-    export PKG_PATH=/tmp/depends
-    if [ "$(echo $(/bin/ls | wc -c))" != 0 ]; then
-	echo "adding dependencies"
-	for i in *.t[bg]z; do
-	    echo "pkg_add $i"
-	    base=$(basename $i .tgz)
-	    base=$(basename $base .tbz)
-	    if pkg_info -q -e $base; then
-		echo "skipping $base, already added"
-	    else
-	        if ! pkg_add $i; then
-		    echo "error in dependency $i, exiting"
-		    echo "1" > /tmp/status
-		    exit 1
-		fi
-	    fi
-	done
-    fi
+  echo "FETCH_DEPENDS=${FD}"
+  echo "PATCH_DEPENDS=${PD}"
+  echo "EXTRACT_DEPENDS=${ED}"
+  echo "BUILD_DEPENDS=${BD}"
+  echo "RUN_DEPENDS=${RD}"
 
-    cd $dir || exit 1
-    pkgname=$(make package-name)
-    echo "================================================================"
-    echo "====================<phase 1: make checksum>===================="
+  add_pkg $FD
 
-    if /pnohang $TIMEOUT /tmp/make.log1 ${pkgname} make checksum; then
-	cat /tmp/make.log1
-echo "0" > /tmp/status
-    else
-	cat /tmp/make.log1
-	echo "1" > /tmp/status
-	echo "================================================================"
-	echo -n "build ended at "
-	date
-    fi
+  #Allow ports to notice they're being run in Tinderbox
+  export PACKAGE_BUILDING=1
+
+  cd $dir || exit 1
+  pkgname=$(make package-name)
+  echo "================================================================"
+  echo "====================<phase 1: make checksum>===================="
+
+  if /pnohang $TIMEOUT /tmp/make.log1 ${pkgname} make checksum; then
+    cat /tmp/make.log1
+    echo "0" > /tmp/status
+  else
+    cleanup 1
+  fi
+
 else
 
-    xvfb=0
-    if which -s Xvfb; then
-	xvfb=1
-	pid=$(echo $$ % 32768 | bc)
-	X11BASE=$(which Xvfb | sed -e 's./bin/Xvfb..')
-	Xvfb :${pid} -fp ${X11BASE}/lib/X11/fonts/misc &
-	DISPLAY=:${pid}
-	export DISPLAY
-    fi
+  cd $dir || exit 1
+  pkgname=$(make package-name)
 
-    echo "====================<phase 2: make package>====================="
-    cat > /tmp/mtree.exclude <<EOF
+  echo "================================================================"
+  echo "====================<phase 2: make extract>===================="
+  add_pkg ${ED}
+  cd $dir
+  /pnohang $TIMEOUT /tmp/make.log2 ${pkgname} make extract || cleanup 2
+  cat /tmp/make.log2
+  del_pkg ${ED}
+
+  echo "================================================================"
+  echo "====================<phase 3: make patch>===================="
+  add_pkg ${PD}
+  cd $dir
+  /pnohang $TIMEOUT /tmp/make.log3 ${pkgname} make patch || cleanup 3
+  cat /tmp/make.log3
+  del_pkg ${PD}
+
+  echo "================================================================"
+  echo "====================<phase 4: make build>===================="
+  add_pkg ${BD}
+
+  xvfb=0
+  if which -s Xvfb; then
+    xvfb=1
+    pid=$(echo $$ % 32768 | bc)
+    X11BASE=$(which Xvfb | sed -e 's./bin/Xvfb..')
+    Xvfb :${pid} -fp ${X11BASE}/lib/X11/fonts/misc &
+    DISPLAY=:${pid}
+    export DISPLAY
+  fi
+
+  cd $dir
+  /pnohang $TIMEOUT /tmp/make.log4 ${pkgname} make build || cleanup 4
+  cat /tmp/make.log4
+
+  echo "================================================================"
+  echo "====================<phase 5: make package>===================="
+  add_pkg ${RD}
+  cat > /tmp/mtree.exclude <<EOF
 ./root/*
 ./var/*
 ./tmp/*
@@ -66,99 +161,74 @@ else
 ./work/*
 ./compat/linux/proc
 EOF
-    mtree -X /tmp/mtree.exclude -xcn -k uid,gid,mode -p / > /tmp/mtree
-    cd $dir || exit 1
-    pkgname=$(make package-name)
-    if /pnohang $TIMEOUT /tmp/make.log2 ${pkgname} make package; then
-	cat /tmp/make.log2
-	echo "0" > /tmp/status
-	prefix=$(make -V PREFIX)
-	echo "================================================================"
-	echo "checking installed files"
-	find ${prefix} \( \( -perm -4000 -o -perm -2000 -a \! -type d \) -o \( -perm -0002 -o -perm -0020 \) \) -a \! -type l -ls | sort > /tmp/list1
-	echo "pkg_delete -f ${pkgname}"
-	pkg_delete -f ${pkgname}
-	find ${prefix} \( \( -perm -4000 -o -perm -2000 -a \! -type d \) -o \( -perm -0002 -o -perm -0020 \) \) -a \! -type l -ls | sort > /tmp/list2
-	if ! diff -qb /tmp/list1 /tmp/list2 2>/dev/null; then
-	    echo "================================================================"
-	    echo "found set[ug]id or world-writable files and directories"
-	    diff -b /tmp/list2 /tmp/list1 | grep '^>'
-	fi
+  mtree -X /tmp/mtree.exclude -xcn -k uid,gid,mode -p / > /tmp/mtree
+  cd $dir
+  if /pnohang $TIMEOUT /tmp/make.log5 ${pkgname} make package; then
+    cat /tmp/make.log5
+    echo "0" > /tmp/status
+    prefix=$(make -V PREFIX)
+    del_pkg ${pkgname}
 
-	mtree -X /tmp/mtree.exclude -x -f /tmp/mtree -p / | egrep -v '^(usr/local/var|usr/local/www/|usr/X11R6/lib/X11/xserver/SecurityPolicy|usr/local/share/nls/POSIX|usr/local/share/nls/en_US.US-ASCII|etc/services|compat |usr/X11R6 |etc/manpath.config|etc/.*.bak|usr/local/info/dir|usr/X11R6/lib/X11/fonts/.*/fonts\.|usr/X11R6/(include|share)/pixmaps|usr/local/lib/xemacs|usr/(X11R6|local)/man/..( |/man. )|usr/X11R6/lib/X11/fonts/TrueType )' > /tmp/list3
+    mtree -X /tmp/mtree.exclude -x -f /tmp/mtree -p / | egrep -v '^(usr/local/var|usr/local/www/|usr/X11R6/lib/X11/xserver/SecurityPolicy|usr/local/share/nls/POSIX|usr/local/share/nls/en_US.US-ASCII|etc/services|compat |usr/X11R6 |etc/manpath.config|etc/.*.bak|usr/local/info/dir|usr/X11R6/lib/X11/fonts/.*/fonts\.|usr/X11R6/(include|share)/pixmaps|usr/local/lib/xemacs|usr/(X11R6|local)/man/..( |/man. )|usr/X11R6/lib/X11/fonts/TrueType )' > /tmp/list3
 
-	if [ -s /tmp/list3 ]; then
-	    cd /
-	    grep ' extra$' /tmp/list3 | awk '{print $1}' | xargs -J % find % -ls > /tmp/list4
-	    grep ' missing$' /tmp/list3 > /tmp/list5
-	    grep -vE ' (extra|missing)$' /tmp/list3 > /tmp/list6
-	    if [ "x${PLISTCHECK}" != "x" ]; then
-		if grep -qE 'usr/(local|X11R6)/(bin/|include/|man/|sbin/|share/|share/|lib/|libdata/|libexec/)' /tmp/list4; then
-		    echo "1" > /tmp/status
-		fi
-		if [ -s /tmp/list5 ]; then
-		    echo "1" > /tmp/status
-		fi
-	    fi
-	    echo "================================================================"
-	fi
-
-	cd /var/db/pkg
-	if [ $(echo $(echo * | wc -c)) != 2 ]; then
-	    echo "deleting dependencies"
-	    prevlist=""
-	    count=1
-	    while [ $(echo $(echo * | wc -c)) != 2 -a $(echo $(echo * | wc -c)) != $(echo $(echo $prevlist | wc -c)) ]; do
-		echo "== phase $count =="
-		prevlist="$(echo *)"
-		for i in *; do
-		    echo "pkg_delete -rf ${i}"
-		    pkg_delete -rf ${i}
-		done
-		count=$(($count + 1))
-	    done
-	fi
-
-	echo
-	echo "=== Checking filesystem state"
-
-	if [ -s /tmp/list4 ]; then
-	    echo "list of extra files and directories in / (not present before this port was installed but present after it was deinstalled)"
-	    cat /tmp/list4
+    if [ -s /tmp/list3 ]; then
+      cd /
+      grep ' extra$' /tmp/list3 | awk '{print $1}' | xargs -J % find % -ls > /tmp/list4
+      grep ' missing$' /tmp/list3 > /tmp/list5
+      grep -vE ' (extra|missing)$' /tmp/list3 > /tmp/list6
+      if [ "x${PLISTCHECK}" != "x" ]; then
+	if grep -qE 'usr/(local|X11R6)/(bin/|include/|man/|sbin/|share/|share/|lib/|libdata/|libexec/)' /tmp/list4; then
+          echo "1" > /tmp/status
 	fi
 	if [ -s /tmp/list5 ]; then
-	    echo "list of files present before this port was installed but missing after it was deinstalled"
-	    cat /tmp/list5
+	  echo "1" > /tmp/status
 	fi
-	if [ -s /tmp/list6 ]; then
-	    echo "list of filesystem changes from before and after port installation and deinstallation"
-	    cat /tmp/list6
-	    if [ "x${PLISTCHECK}" != "x" ]; then
-		echo "1" > /tmp/status
-	    fi
-	fi
-
-	if grep -q PORT_TRIES_TO_WRITE_TO_HOME /tmp/make.log2; then
-	    echo "1" > /tmp/status
-	fi
-    else
-	cat /tmp/make.log2
-	echo "1" > /tmp/status
+      fi
+      echo "================================================================"
     fi
 
-    if [ ${xvfb} = 1 ]; then
-	kill $(jobid %1)
+    # BUILD_DEPENDS need to be present at install-time, e.g. gmake
+    # Concatenate and remove duplicates
+    BRD=$(echo $BD $RD | tr ' ' '\n' | sort -u | tr '\n' ' ')
+    del_pkg ${BRD}
+    cd /var/db/pkg
+    if [ $(echo $(echo * | wc -c)) != 2 ]; then
+      echo "leftover packages:" *
+      del_pkg *
     fi
 
-    if [ -e ${dir}/.keep ]; then
-	cd ${dir}
-	objdir=$(make -V WRKDIR)
-	tar cfjC /tmp/work.tbz ${objdir}/.. work
-    fi
+    echo
+    echo "=== Checking filesystem state"
 
-    echo "================================================================"
-    echo -n "build ended at "
-    date
+    if [ -s /tmp/list4 ]; then
+      echo "list of extra files and directories in / (not present before this port was installed but present after it was deinstalled)"
+      cat /tmp/list4
+    fi
+    if [ -s /tmp/list5 ]; then
+      echo "list of files present before this port was installed but missing after it was deinstalled)"
+      cat /tmp/list5
+    fi
+    if [ -s /tmp/list6 ]; then
+      echo "list of filesystem changes from before and after port installation and deinstallation"
+      cat /tmp/list6
+      if [ "x${PLISTCHECK}" != "x" ]; then
+        echo "1" > /tmp/status
+      fi
+    fi
+  else
+    cleanup 5
+  fi
+
+  if [ ${xvfb} = 1 ]; then
+    kill $(jobid %1)
+  fi
+
+  if [ -e ${dir}/.keep ]; then
+    cd ${dir}
+    objdir=$(make -V WRKDIR)
+    tar cfjC /tmp/work.tbz ${objdir}/.. work
+  fi
+
 fi
 
 exit 0
