Without even releasing 1.0, I have gone through a redesign to make the tinderbox more flexible.  It is back to a state where tinderbuild can automatically build packages.  The rest of the automation still needs some work.

diff --git a/create_new_jail b/create_new_jail
--- a/create_new_jail
+++ b/create_new_jail
@@ -1,41 +1,70 @@
 #!/bin/sh
 
+usage () {
+    echo "usage: $0 -n <jail name> -t <jail tag> [-d <description>] [-u <update command|CVSUP|NONE>]"
+    exit 1
+}
+
 pb=/space
 suphost=cvsup12.FreeBSD.org
 cvsup_compress= #*default compress
 
-if [ $# -lt 2 ]; then
-    echo "usage: $0 <jail name> <jail tag>"
-    exit 1
+args=$(getopt n:t:u:d: $*)
+
+if [ $? != 0 ]; then
+    usage
 fi
 
-jail_name=$1
-jail_tag=$2
+jail_name=""
+jail_tag=""
+descr=""
+update_cmd=""
+uc=""
 
-_jails=$(${pb}/scripts/list_jails)
+set -- $args
+
+for i; do
+    case "$i" in
+	-n)
+	  jail_name="$2"; shift;
+	  shift;;
+	-t)
+	  jail_tag="$2"; shift;
+	  shift;;
+	-d)
+	  descr="$2"; shift;
+	  shift;;
+	-u)
+	  update_cmd="$2"; shift;
+	  shift;;
+	--)
+	  shift; break;;
+    esac
+done
+
+if [ -z "${jail_name}" -o -z "${jail_tag}" ]; then
+    usage
+fi
+
+_jails=$(${pb}/scripts/tc listJails)
 if echo ${_jails} | grep -qw ${jail_name}; then
-    echo "Jail ${jail_name} already exists."
+    echo "ERROR: Jail, \"${jail_name}\" already exists."
     exit 1
 fi
 
-echo -n "INFO: Creating directories and supfiles for new jail..."
-rm -rf ${pb}/${jail_name}
+if [ -z "${update_cmd}" ]; then
+    update_cmd="/usr/local/bin/cvsup -g ${pb}/jails/${jail_name}/src-supfile"
+elif [ "${update_cmd}" = "NONE" ]; then
+    update_cmd=""
+    uc="-u NONE"
+else
+    uc="-u ${update_cmd}"
+fi
 
-mkdir -p ${pb}/${jail_name}/ports
-mkdir -p ${pb}/${jail_name}/src
+echo -n "INFO: Creating directories and supfile for new jail..."
+rm -rf ${pb}/jails/${jail_name}
 
-mkdir -p ${pb}/logs/${jail_name}
-mkdir -p ${pb}/errors/${jail_name}
-
-cat > ${pb}/${jail_name}/ports-supfile << EOSF
-*default host=${suphost}
-*default base=${pb}/${jail_name}
-*default prefix=${pb}/${jail_name}
-*default release=cvs tag=.
-*default delete use-rel-suffix
-${cvsup_compress}
-ports-all
-EOSF
+mkdir -p ${pb}/jails/${jail_name}/src
 
 cat > ${pb}/${jail_name}/src-supfile << EOSF
 *default host=${suphost}
@@ -49,30 +78,22 @@ EOSF
 
 echo "DONE."
 
+# Add the new jail to the datastore.
+echo -n "INFO: Adding jail to datastore..."
+if [ ! -z "${descr}" ]; then
+    descr="-d ${descr}"
+fi
+${pb}/scripts/tc addJail -n ${jail_name} -t ${jail_tag} ${descr} ${uc}
+
+if [ $? != 0 ]; then
+    echo "FAILED."
+    exit 1
+fi
+
+echo "DONE."
+
 echo "INFO: Initializing new jail..."
 ${pb}/scripts/mkjail ${jail_name}
-
-if [ $? != 0 ]; then
-    echo "FAILED."
-    exit 1
-fi
-
-echo "DONE."
-
-# mkjail will cvsup src, but we need to cvsup ports.
-echo -n "INFO: CVSup'ing ports tree..."
-/usr/local/bin/cvsup -g ${pb}/${jail_name}/ports-supfile > /dev/null 2>&1
-
-if [ $? != 0 ]; then
-    echo "FAILED."
-    exit 1
-fi
-
-echo "DONE."
-
-# Add the new jail to the database, and we're done.
-echo -n "INFO: Adding jail to datastore..."
-${pb}/scripts/add_jail -n ${jail_name} -t ${jail_tag}
 
 if [ $? != 0 ]; then
     echo "FAILED."
diff --git a/tinderbuild b/tinderbuild
--- a/tinderbuild
+++ b/tinderbuild
@@ -3,13 +3,13 @@
 pb=/space
 
 usage () {
-    echo "usage: $0 -j <jail name> [portdir/portname [...]]"
+    echo "usage: $0 -b <build name> [portdir/portname [...]]"
 }
 
 . ${pb}/scripts/buildenv
 
-_jails=$(${pb}/scripts/list_jails)
-jail=""
+_builds=$(${pb}/scripts/tc listBuilds)
+build=""
 ports=""
 
 init=0
@@ -17,12 +17,12 @@ cleanpackages=0
 
 while [ $# -gt 0 ]; do
     case "x$1" in
-      x-j)
+      x-b)
         shift
-        if echo ${_jails} | grep -qw "$1"; then
-	    jail=$1
+        if echo ${_builds} | grep -qw "$1"; then
+	    build=$1
 	else
-	    echo "ERROR: Jail, \"$1\" is not a valid jail."
+	    echo "ERROR: Build, \"$1\" is not a valid build."
 	    exit 1
 	fi
 	;;
@@ -42,16 +42,19 @@ while [ $# -gt 0 ]; do
     shift
 done
 
-if [ "x${jail}" = "x" ]; then
+if [ "x${build}" = "x" ]; then
     usage
     exit 1
 fi
 
+jail=$(${pb}/scripts/tc getJailForBuild -b ${build})
+portstree=$(${pb}/scripts/tc getPortsTreeForBuild -b ${build})
+
 # Setup the environment for this jail.
-buildenv ${pb} ${jail}
+buildenv ${pb} ${build} ${jail} ${portstree}
 
 # Remove the make logs.
-rm -f ${pb}/${jail}/make.*
+rm -f ${pb}/${build}/make.*
 
 # First we check to see if we need to clean out old packages.
 if [ "$cleanpackages" = "1" ]; then
@@ -61,15 +64,21 @@ fi
 mkdir -p ${PACKAGES}
 
 # Next, we build a Makefile for each jail.
-${pb}/scripts/makemake ${jail} ${ports}
+${pb}/scripts/makemake ${build} ${ports}
+
+if [ $? != 0 ]; then
+    echo "ERROR: Failed to generate Makefile for ${build}"
+    exit 1
+fi
 
 # Then we check to see if we need to create our jail directory.
-if [ "$init" = "1" -o \( ! -d ${pb}/jails/${jail} -a ! -f ${pb}/repo/${jail}.tar \) ]; then
-    echo "INFO: Initializing a new jail directory for ${jail}..."
+if [ "$init" = "1" -o \( ! -d ${pb}/${build} -a ! -f ${pb}/jails/${jail}/${jail}.tar \) ]; then
+    echo "INFO: Initializing a new build directory for ${build}..."
     ${pb}/scripts/mkjail ${jail}
-elif [ ! -d ${pb}/jails/${jail} -a -f ${pb}/repo/${jail}.tar ]; then
-    echo "INFO: Creating jail directory for ${jail} from repository..."
-    ${pb}/scripts/mkjailfromrepo ${jail}
+    ${pb}/scripts/mkbuild ${build}
+elif [ ! -d ${pb}/${build} -a -f ${pb}/jails/${jail}/${jail}.tar ]; then
+    echo "INFO: Creating build directory for ${build} from repository..."
+    ${pb}/scripts/mkbuild ${build}
 fi
 
 # We do this in two phases to make sure we get everything.
@@ -78,7 +87,7 @@ echo "building packages (phase 1)"
 echo "================================================"
 echo "started at $(date)"
 phase1start=$(date +%s)
-cd ${PACKAGES}/All && make -k -j1 all > ${pb}/${jail}/make.0 2>&1 </dev/null
+cd ${PACKAGES}/All && make -k -j1 all > ${pb}/builds/${build}/make.0 2>&1 </dev/null
 echo "ended at $(date)"
 phase1end=$(date +%s)
 echo "phase 1 took $(date -u -j -r $(($phase1end - $phase1start)) | awk '{print $4}')" 
@@ -90,7 +99,7 @@ echo "building packages (phase 2)"
 echo "================================================"
 echo "started at $(date)"
 phase2start=$(date +%s)
-cd ${PACKAGES}/All && make -k -j1 all > ${pb}/${jail}/make.1 2>&1 </dev/null
+cd ${PACKAGES}/All && make -k -j1 all > ${pb}/builds/${build}/make.1 2>&1 </dev/null
 echo "ended at $(date)"
 phase2end=$(date +%s)
 echo "phase 2 took $(date -u -j -r $(($phase2end - $phase2start)) | awk '{print $4}')"
