* Correct a typo * Add a new -i flag to control whether or not the build show be initialized   at the time of creation
Submitted by:	ade

diff --git a/create_new_build b/create_new_build
--- a/create_new_build
+++ b/create_new_build
@@ -24,12 +24,12 @@
 # OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 # SUCH DAMAGE.
 #
-# $MCom: portstools/tinderbox/create_new_build,v 1.10 2005/07/10 07:25:59 oliver Exp $
+# $MCom: portstools/tinderbox/create_new_build,v 1.11 2005/07/19 18:32:45 marcus Exp $
 #
 
 
 usage () {
-    echo "usage: $0 -n <build name> -j <jail name> -p <portstree name> [-d <build description>]"
+    echo "usage: $0 -n <build name> -j <jail name> -p <portstree name> [-d <build description>] [-i]"
     exit 1
 }
 
@@ -44,10 +44,11 @@ pb=$(type "$pb" | sed 's/^.* //g')
 pb=$(realpath $(dirname $pb))
 pb=${pb%%/scripts}
 
-buil_name=""
+build_name=""
 jail=""
 portstree=""
 descr=""
+init=0
 
 while [ $# -gt 0 ]; do
     case "x$1" in
@@ -62,6 +63,9 @@ while [ $# -gt 0 ]; do
 	  ;;
 	x-d)
 	  descr="$2"; shift;
+	  ;;
+	x-i)
+	  init=1;
 	  ;;
 	*)
 	  usage
@@ -110,12 +114,14 @@ fi
 
 echo "DONE."
 
-echo -n "INFO: Initializing new build..."
-${pb}/scripts/mkbuild ${build_name}
+if [ ${init} = 1 ]; then
+    echo -n "INFO: Initializing new build..."
+    ${pb}/scripts/mkbuild ${build_name}
 
-if [ $? != 0 ]; then
-    echo "FAILED."
-    exit 1
+    if [ $? != 0 ]; then
+	echo "FAILED."
+	exit 1
+    fi
 fi
 
 echo "DONE."
