Some more fixes now that I've seen the build work a few times.

diff --git a/mkbuild b/mkbuild
--- a/mkbuild
+++ b/mkbuild
@@ -2,16 +2,23 @@
 
 pb=/space
 
+_builds=$(${pb}/scripts/tc listBuilds)
+
 if [ -z "$1" ]; then
     echo "Please specify a build name."
     echo "Current build names are:"
-    for i in `${pb}/scripts/tc listBuilds`; do
+    for i in ${_builds}; do
 	echo "	${i}"
     done
     exit 1
 fi
 
 build=$1
+
+if ! echo ${_builds} | grep -qw ${build}; then
+    echo "ERROR: Unknown build, \"${build}\"."
+    exit 1
+fi
 
 jail=$(${pb}/scripts/tc getJailForBuild -b ${build})
 
diff --git a/mkjail b/mkjail
--- a/mkjail
+++ b/mkjail
@@ -2,10 +2,12 @@
 
 pb=/space
 
+_jails=$(${pb}/scripts/tc listJails)
+
 if [ -z "$1" ]; then
     echo "Please specify a jail name."
     echo "Current jails are:"
-    for i in `${pb}/scripts/tc listJails`; do
+    for i in ${_jails}; do
 	echo "	${i}"
     done
     exit 1
@@ -15,10 +17,15 @@ fi
 
 jail=$1
 
-# We only care about SRCBASE, so the other parameters can be anything.
-buildenv ${pb} "NULL" ${jail} "NULL" "NULL"
+if ! echo ${_jails} | grep -qw ${jail}; then
+    echo "ERROR: Unknown jail, \"${jail}\"."
+    exit 1
+fi
 
-update_cmd=`${pb}/scripts/tc getSrcUpdateCmd -j ${jail}`
+# We only care about SRCBASE, so the other parameters can be anything.
+buildenv ${pb} "NULL" ${jail} "NULL"
+
+update_cmd=$(${pb}/scripts/tc getSrcUpdateCmd -j ${jail})
 if [ ! -z "${update_cmd}" ]; then
     eval ${update_cmd} > /dev/null 2>&1
 fi
diff --git a/tinderbuild b/tinderbuild
--- a/tinderbuild
+++ b/tinderbuild
@@ -51,6 +51,18 @@ if [ "x${build}" = "x" ]; then
     exit 1
 fi
 
+lock=${pb}/builds/${build}/lock
+
+if [ -e ${lock} ]; then
+    echo "ERROR: Lock file ${lock} exists; exiting."
+    exit 1
+fi
+
+touch ${lock}
+
+# XXX This is a crude hack to normalize ${ports}
+ports=$(echo ${ports})
+
 jail=$(${pb}/scripts/tc getJailForBuild -b ${build})
 portstree=$(${pb}/scripts/tc getPortsTreeForBuild -b ${build})
 
