Exit if Lock file could not be created
Approved by:	marcus

diff --git a/tinderbuild b/tinderbuild
--- a/tinderbuild
+++ b/tinderbuild
@@ -24,7 +24,7 @@
 # OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 # SUCH DAMAGE.
 #
-# $MCom: portstools/tinderbox/tinderbuild,v 1.29 2005/07/03 07:26:02 oliver Exp $
+# $MCom: portstools/tinderbox/tinderbuild,v 1.30 2005/07/09 06:23:00 oliver Exp $
 #
 
 
@@ -129,7 +129,10 @@ if [ -e ${lock} ]; then
     exit 1
 fi
 
-touch ${lock}
+if ! touch ${lock} ; then
+    echo "ERROR: Lock file ${lock} could not be created; exiting."
+    exit 1
+fi
 
 # Let the datastore known what we're doing.
 ${pb}/scripts/tc updateBuildStatus -b ${build} -s PREPARE
