Introduce a number of fairly extensive cleanups to the tinderbox code:
* remove the 'tc makeBuild' command, it's only used by 'tc tinderbuild'
* convert 'tc updatePortsTree' from perl to shell
* replace 'tc getSrcUpdateCmd' and 'tc getPortsUpdateCmd' with a single
  generic 'tc getUpdateCmd' to reduce code duplication
* add an environmental variable, TINDERBOX_QUERY_DEBUG which, if set,
  prints out the queries to the SQL datastore as they are executed
* rework the argument passing from tinderbuild -> makemake,
  tinderbuild -> portbuild, and portbuild -> buildscript to only use
  command line options, rather than the mix of argument processing
  and setting of environmental variables
* remove the -trybroken option from tinderbuild and portbuild, it wasn't
  actually doing anything, presumably a left-over from pointyhat
* migrate most of the additional build tree setup code (such as mountpoints)
  away from portbuild into tinderbuild, so it is called only once
* normalize a number of usage strings in tc_commands.pl for consistency
* add a -I (don't initialize) option to createPortsTree, similar to
  createBuild
* the output of 'make world' and 'make distribution' is now stored
  in the jail directory as world.log and distribution.log respectively
* use either the jail directory, or a subdirectory of JAIL_OBJDIR for
  the src/ tree, generated obj/ tree, and produced world snap.  /usr/obj
  is no longer touched at all by tinderbox.  This further allows jails/
  to be a symbolic link back to a central filestore, allowing the results
  of a jail build to be used by multiple machines
* re-order commands in tc_command.sh into functional groups
* extensive reworking of requestMount and cleanupMounts to allow for
  an optional destination directory to be specified.  Clean up the
  various references to requestMount with equivalent cleanupMounts so
  that dangling filesystem mounts should be a thing of the past
* rework the per-build,jail,portstree environmental variable settings
  in buildenv to use scripts/etc/env/{global,jail.<J>,portstree.<P>,
  build.<B>} rather than having them scattered around the tinderbox
  filesystems

There's a few more cleanups to be done yet, but this has most of the
groundwork laid for the beginnings of a LAN-distributed tinderbox
system, driven by the webUI, whilst still maintaining full backwards
compatibility with single-host tinderboxes that are run from the
command line.

diff --git a/lib/portbuild b/lib/portbuild
--- a/lib/portbuild
+++ b/lib/portbuild
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 usage () {
-    echo "usage: $0 <build name> <jail name> <portstree name> [-noclean] [-plistcheck] [-nullfs] [-fetch-original] [-nolog] [-trybroken] ED PD FD BD RD pkgname dirname"
+    echo "usage: $0 <build name> <jail name> <portstree name> [-noclean] [-plistcheck] [-nullfs] [-fetch-original] [-nolog] ED PD FD BD RD pkgname dirname"
     exit 1
 }
 
@@ -13,8 +13,6 @@ cleanup()
     cleandirs=$4
     pkgname=$5
     build=$6
-
-    cleanupMounts -d build -b $(basename $chroot)
 
     if [ -n "${DISTFILE_CACHE}" ]; then
 	if [ -f ${chroot}${DISTCACHE}/.lock ]; then
@@ -51,68 +49,64 @@ cleanup()
 error=0
 init=0
 noclean=0
-nullfs=0
+nullfs=""
 fetchorig=0
 nolog=0
+plistcheck=""
+nice=0
 
 # check parameter count
 if [ $# -lt 10 ]; then
     usage
 fi
 
+# argument processing
+
+# first, strip off the first 3 components as {build,jail,portstree}
 build=$1
-shift
-jail=$1
-shift
-portstree=$1
-shift
+jail=$2
+portstree=$3
+shift 3
 
-# Default niceness value
-nice=0
+# process -arguments in any order.  previously, the code expected to
+# see arguments in a very specific way, and silently did weird and
+# wonderful things if they weren't
+doneargs=0
+while [ $# -gt 0 -a ${doneargs} = 0 ]; do
 
-if [ "x$1" = "x-noclean" ]; then
-    noclean=1
-    shift
-fi
+    case "x$1" in
 
-plistcheck=0
-if [ "x$1" = "x-plistcheck" ]; then
-    plistcheck=1
-    export PLISTCHECK=1
-    shift
-fi
+    x-noclean)		noclean=1
+			shift;;
 
-if [ "x$1" = "x-nullfs" ]; then
-    nullfs=1
-    shift
-fi
+    x-plistcheck)	plistcheck="plistcheck"
+			shift;;
 
-if [ "x$1" = "x-fetch-original" ]; then
-    fetchorig=1
-    shift
-fi
+    x-nullfs)		nullfs="-n"
+			shift;;
 
-if [ "x$1" = "x-nolog" ]; then
-    nolog=1
-    shift
-fi
+    x-fetch-original)	fetchorig=1
+			shift;;
 
-if [ "x$1" = "x-trybroken" ]; then
-    export TRYBROKEN=1
-    shift
-fi
+    x-nolog)		nolog=1
+			shift;;
 
+    x-*)		echo "ERROR: portbuild: unknown argument: $1"
+			exit 1;;
+
+    *)			doneargs=1;;
+
+    esac
+done
+
+# Finally, strip off the dependency lists, package name, and port directory
 ED=$1
 PD=$2
 FD=$3
 BD=$4
 RD=$5
-
-buildenv ${jail} ${portstree} ${build}
-
 pkgname=$(basename $6 ${PKGSUFFIX})
 dirname=$7
-shift 2
 
 echo ${pkgname}
 echo ${dirname}
@@ -158,36 +152,13 @@ ulimit -t 3600
 # directories to clean
 cleandirs="/usr/local /usr/X11R6 /compat /var/db/pkg"
 
-# 15 minutes
-export FTP_TIMEOUT=900
-export HTTP_TIMEOUT=900
-
-export FTP_PASSIVE_MODE=yes
-
-export BATCH=1
-export PACKAGE_BUILDING=1
-
-export PORTOBJFORMAT=elf
-
-export USA_RESIDENT=yes
-
 export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/X11R6/bin
-
-# Just to be shure we start in a clean build-tree
-cleanupMounts -d build -b ${build}
 
 if [ x"${CCACHE_ENABLED}" = x"1" ]; then
     # XXX We need to do this since certain ports (e.g. cdrtools) don't
     # respect CC the way they should (thanks for the tip, Adam).
     export PATH=/opt:${PATH}
 fi
-
-# Use the *.env file to specify per-jail, per-portstree, and per-build
-# environment variables.
-[ -f ${pb}/jails/${jail}/jail.env ] && . ${pb}/jails/${jail}/jail.env
-[ -f ${pb}/portstrees/${portstree}/portstree.env ] && \
-	. ${pb}/portstrees/${portstree}/portstree.env
-[ -f ${pb}/builds/${build}/build.env ] && . ${pb}/builds/${build}/build.env
 
 echo "building $pkgname in $chroot"
 
@@ -198,60 +169,10 @@ packages=${pb}/packages/${build}
 
 major_version=$(echo ${jail} | sed -E -e 's|(^.).*$|\1|')
 
-if [ "${major_version}" = "4" ]; then
-    mkdir -p ${chroot}/libexec
-    mkdir -p ${chroot}/lib
-    if [ "${ARCH}" = "i386" -o "${ARCH}" = "amd64" ]; then
-        cp -p /sbin/mount_linprocfs /sbin/mount /sbin/umount ${chroot}/sbin
-        cp -p /lib/libufs.so.[0-9]* ${chroot}/lib
-    fi
-    cp -p /libexec/ld-elf.so.1 ${chroot}/libexec
-    cp -p /lib/libkvm.so.[0-9]* /lib/libm.so.[0-9]* ${chroot}/lib
-    if [ -f /lib/libc.so.6 ]; then
-	if [ -f ${chroot}/lib/libc.so.6 ]; then
-		chflags noschg ${chroot}/lib/libc.so.6
-	fi
-	cp -p /lib/libc.so.6 ${chroot}/lib
-    else
-	if [ -f ${chroot}/lib/libc.so.5 ]; then
-		chflags noschg ${chroot}/lib/libc.so.5
-	fi
-	cp -p /lib/libc.so.5 ${chroot}/lib
-    fi
-elif [ "${major_version}" = "6" -o "${major_version}" = "7" ]; then
-    if [ -f /lib/libc.so.5 ]; then
-        if [ -f ${chroot}/lib/libc.so.5 ]; then
-	    chflags noschg ${chroot}/lib/libc.so.5
-        fi
-        cp -p /lib/libc.so.5 ${chroot}/lib
-    fi
-elif [ "${major_version}" = "5" ]; then
-    if [ -f /lib/libc.so.6 ]; then
-        if [ -f ${chroot}/lib/libc.so.6 ]; then
-	    chflags noschg ${chroot}/lib/libc.so.6
-        fi
-        cp -p /lib/libc.so.6 ${chroot}/lib
-    fi
-fi
-cp -p /rescue/ps ${chroot}/bin
-cp -p /usr/bin/killall ${chroot}/usr/bin
-
-# XXX This is a hack to fix some recent pkg_add problems in some releases.
-if [ -f ${pb}/jails/${jail}/pkg_install.tar ]; then
-    tar -C ${chroot} -xf ${pb}/jails/${jail}/pkg_install.tar
-fi
-
-if [ x"${CCACHE_ENABLED}" = x"1" -a -f ${pb}/jails/${jail}/ccache.tar ]; then
-    tar -C ${chroot} -xf ${pb}/jails/${jail}/ccache.tar
-fi
-
-echo ${OSREL}-${BRANCH} > ${chroot}/usr/bin/UNAME_VERSION
-
 trap  "cleanup ${chroot} ${noclean} ${error} \"${cleandirs}\" ${pkgname} ${build}" 1 2 3 9 10 11 15
 
 if [ -n "${DISTFILE_CACHE}" ]; then
     export DISTCACHE=/distcache
-    mkdir -p ${chroot}${DISTCACHE}
     if [ ${fetchorig} = 0 ]; then
         _MASTER_SITE_OVERRIDE='file:///distcache/${DIST_SUBDIR}/'
         export MASTER_SITE_OVERRIDE="${_MASTER_SITE_OVERRIDE} ${MASTER_SITE_OVERRIDE}"
@@ -259,27 +180,10 @@ if [ -n "${DISTFILE_CACHE}" ]; then
 fi
 
 rm -rf ${chroot}/tmp/*
-cd ${chroot}/tmp
-mkdir -p depends distfiles packages
+mkdir -p ${chroot}/tmp/depends ${chroot}/tmp/distfiles ${chroot}/tmp/packages
 
-echo "building ${pkgname} in directory ${chroot}" | tee ${chroot}/tmp/${pkgname}.log
-
-# If we're using a central distfile repository, mount it now
-if [ -n "${DISTFILE_CACHE}" ] ; then
-	requestMount -d distcache -b ${build} -s "${DISTFILE_CACHE}"
-fi
-
-# intentionally set up ${PORTSDIR} with symlink to catch broken ports
-mkdir -p ${chroot}/a/ports
-rm -rf ${chroot}/usr/ports
-
-if [ ${nullfs} -eq 1 ] ; then
-	requestMount -n -r -d buildports -b ${build}
-else
-	requestMount -r -d buildports -b ${build}
-fi
-
-ln -sf ../a/ports ${chroot}/usr/ports
+echo "building ${pkgname} in directory ${chroot}" | \
+    tee ${chroot}/tmp/${pkgname}.log
 
 # Don't build in a world-writable directory because some ports hardcode
 # this path and try to load things from it at runtime, which is bad for
@@ -287,37 +191,7 @@ ln -sf ../a/ports ${chroot}/usr/ports
 rm -rf ${chroot}/${WRKDIRPREFIX}
 mkdir -p ${chroot}/${WRKDIRPREFIX}
 
-mkdir -p ${chroot}/usr/src
-
-if [ ${nullfs} -eq 1 ] ; then
-	requestMount -n -r -d buildsrc -b ${build}
-else
-	requestMount -r -d buildsrc -b ${build}
-fi
-
-mount -t devfs foo ${chroot}/dev
-
-if [ x"${CCACHE_ENABLED}" = x"1" ]; then
-    mkdir -p ${pb}/${CCACHE_DIR}/${build}
-    mkdir -p ${chroot}/${CCACHE_DIR}
-    if [ x"${CCACHE_JAIL}" = x"1" ]; then
-	if [ ${nullfs} -eq 1 ] ; then
-		requestMount -n -d ccache -s ${pb}/${CCACHE_DIR}/${jail} -b ${build}
-	else
-		requestMount -d ccache -s ${pb}/${CCACHE_DIR}/${jail} -b ${build}
-	fi
-    else
-	if [ ${nullfs} -eq 1 ] ; then
-		requestMount -n -d ccache -s ${pb}/${CCACHE_DIR}/${build} -b ${build}
-	else
-		requestMount -d ccache -s ${pb}/${CCACHE_DIR}/${build} -b ${build}
-	fi
-    fi
-    if [ -n "${CCACHE_MAX_SIZE}" ]; then
-        # Example: CCACHE_MAX_SIZE=2G (2 GB)
-        # G=GB, M=MB, K=KB
-        chroot ${chroot} ccache -M ${CCACHE_MAX_SIZE}
-    fi
+if [ x"${CCACHE_ENABLED}" ]; then
     unset CCACHE_DISABLE
 fi
 
@@ -330,31 +204,23 @@ done
 
 rm -rf ${chroot}/var/db/pkg/*
 
-mtree -deU -f ${chroot}/etc/mtree/BSD.root.dist -p ${chroot} \
-  >/dev/null 2>&1
-mtree -deU -f ${chroot}/etc/mtree/BSD.var.dist -p ${chroot}/var \
-  >/dev/null 2>&1
-mtree -deU -f ${chroot}/etc/mtree/BSD.usr.dist -p ${chroot}/usr \
-  >/dev/null 2>&1
-mtree -deU -f ${chroot}/etc/mtree/BSD.local.dist -p ${chroot}/usr/local \
-  >/dev/null 2>&1
+# reset mtrees for plist checking
+mtree -deU -f ${chroot}/etc/mtree/BSD.root.dist \
+      -p ${chroot} >/dev/null 2>&1
+mtree -deU -f ${chroot}/etc/mtree/BSD.var.dist \
+      -p ${chroot}/var >/dev/null 2>&1
+mtree -deU -f ${chroot}/etc/mtree/BSD.usr.dist \
+      -p ${chroot}/usr >/dev/null 2>&1
+mtree -deU -f ${chroot}/etc/mtree/BSD.local.dist \
+      -p ${chroot}/usr/local >/dev/null 2>&1
 
-mkdir ${chroot}/usr/X11R6
-if [ $X_WINDOW_SYSTEM = "xfree86-3" ]; then
-    mtree -deU -f ${chroot}/usr/src/etc/mtree/BSD.x11.dist -p ${chroot}/usr/X11R6 >/dev/null 2>&1
-elif [ $X_WINDOW_SYSTEM = "xorg" ]; then
-    mtree -deU -f ${chroot}/a/ports/x11-servers/xorg-server/files/BSD.x11-xorg.dist -p ${chroot}/usr/X11R6 \
-    >/dev/null 2>&1
-else
-    mtree -deU -f ${chroot}/usr/src/etc/mtree/BSD.x11-4.dist -p ${chroot}/usr/X11R6 \
-    >/dev/null 2>&1
-fi
-
-if [ ${ARCH} = "i386" -o ${ARCH} = "amd64" ]; then
-    # JDK ports need linprocfs :(
-    mkdir -p ${chroot}/compat/linux/proc
-    chroot ${chroot} mount_linprocfs linprocfs /compat/linux/proc
-fi
+case "${X_WINDOW_SYSTEM}" in
+"xfree86-3")	_X_MTREE="BSD.x11.dist";;
+"xorg")		_X_MTREE="BSD.x11-xorg.dist";;
+*)		_X_MTREE="BSD.x11-4.dist";;
+esac
+mtree -deU -f ${chroot}/etc/${_X_MTREE} \
+      -p ${chroot}/usr/X11R6 >/dev/null 2>&1
 
 _ldconfig_dirs="/lib /usr/lib /usr/lib/compat"
 ldconfig_dirs=""
@@ -382,16 +248,7 @@ while [ $# -gt 0 ]; do
     shift
 done
 
-if ! cp -p ${pb}/scripts/lib/buildscript ${chroot}; then
-    error=3
-    cleanup ${chroot} ${noclean} ${error} "${cleandirs}" ${pkgname} ${build}
-fi
-if ! cc -o ${chroot}/pnohang -static ${pb}/scripts/lib/pnohang.c; then
-    error=4
-    cleanup ${chroot} ${noclean} ${error} "${cleandirs}" ${pkgname} ${build}
-fi
-
-chroot ${chroot} /buildscript ${dirname} 1 "$ED" "$PD" "$FD" "$BD" "$RD" 2>&1 | tee -a ${chroot}/tmp/${pkgname}.log
+chroot ${chroot} /buildscript ${dirname} 1 "$ED" "$PD" "$FD" "$BD" "$RD" "${plistcheck}" 2>&1 | tee -a ${chroot}/tmp/${pkgname}.log
 if [ -f ${chroot}/tmp/status ]; then
     error=$(cat ${chroot}/tmp/status)
 else
@@ -426,7 +283,7 @@ if [ "${error}" = 0 ]; then
 	fi
     fi
 
-    chroot ${chroot} /usr/bin/nice -n $nice /buildscript ${dirname} 2  "$ED" "$PD" "$FD" "$BD" "$RD" > ${chroot}/tmp/${pkgname}.log2 2>&1
+    chroot ${chroot} /usr/bin/nice -n $nice /buildscript ${dirname} 2  "$ED" "$PD" "$FD" "$BD" "$RD" "${plistcheck}" > ${chroot}/tmp/${pkgname}.log2 2>&1
 
     grep pnohang ${chroot}/tmp/${pkgname}.log2
     cat ${chroot}/tmp/${pkgname}.log2 >> ${chroot}/tmp/${pkgname}.log
