Add a new Hook for pre and post Checksum.
Requested by:	itetcu

diff --git a/lib/portbuild b/lib/portbuild
--- a/lib/portbuild
+++ b/lib/portbuild
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $MCom: portstools/tinderbox/lib/portbuild,v 1.136 2010/05/08 18:23:35 marcus Exp $
+# $MCom: portstools/tinderbox/lib/portbuild,v 1.137 2010/10/31 21:49:57 marcus Exp $
 
 . ${pb}/scripts/lib/tinderlib.sh
 
@@ -330,12 +330,22 @@ while [ $# -gt 0 ]; do
     shift
 done
 
+
+execute_hook "prePortChecksum" "PACKAGE_NAME=${pkgname} BUILD=${build} JAIL=${jail} PORTSTREE=${portstree} CHROOT=${chroot} PORTDIR=${portdir} PB=${pb} TOTAL_SIZE=${total_size}"
+if [ $? -ne 0 ]; then
+    echo "portbuild: Terminating build for ${pkgname} since prePortChecksum hook failed"
+    ${tc} updatePortStatus -d ${portdir} -b ${build} -L -s FAIL -v ${pkgname} -r "hook"
+    mark_failed ${tc} ${build} ${pkgname} ${portdir}
+    exit 1
+fi
+
 chroot ${chroot} /buildscript ${dirname} 1 "$ED" "$PD" "$FD" "$BD" "$RD" "${plistcheck}" 2>&1 | tee -a ${chroot}/tmp/${pkgname}.log
 if [ -f ${chroot}/tmp/status ]; then
     error=$(cat ${chroot}/tmp/status)
 else
     error=255
 fi
+execute_hook "postPortChecksum" "PACKAGE_NAME=${pkgname} BUILD=${build} JAIL=${jail} PORTSTREE=${portstree} CHROOT=${chroot} PORTDIR=${portdir} ERROR=${error} PB=${pb} TOTAL_SIZE=${total_size}"
 
 last_version=$(${tc} getPortLastBuiltVersion -d ${portdir} -b ${build})
 logsDir=$(tinderLoc buildlogs ${build})
